$(document).ready(function () {
    $('input.mood-autocomplete').autocomplete({
        data: {
            "joyous": null,
            "happy": null,
            "pleased": null,
            "feel well": null,
            "amorous": null,
            "glad": null,
            "solemn": null,
            "serene": null,
            "content": null,
            "at ease": null,
            "satisfied": null,
            "friendly": null,
            "relaxed": null,
            "calm": null,
            "excited": null,
            "self confident": null,
            "courageous": null,
            "delighted": null,
            "adventurous": null,
            "triumphant": null,
            "enthusiastic": null,
            "determined": null,
            "amused": null,
            "interested": null,
            "confident": null,
            "hopeful": null,
            "attentive": null,
            "contemplative": null,
            "peaceful": null,
            "aroused": null,
            "astonished": null,
            "lusting": null,
            "conceited": null,
            "ambitious": null,
            "superior": null,
            "convinced": null,
            "light hearted": null,
            "passionate": null,
            "expectant": null,
            "impressed": null,
            "longing": null,
            "pensive": null,
            "serious": null,
            "polite": null,
            "conscientious": null,
            "compassionate": null,
            "reverent": null,
            "sleepy": null,
            "tired": null,
            "bellicose": null,
            "alarmed": null,
            "tense": null,
            "afraid": null,
            "hostile": null,
            "envious": null,
            "angry": null,
            "enraged": null,
            "annoyed": null,
            "jealous": null,
            "indignant": null,
            "impatient": null,
            "suspicious": null,
            "apathetic": null,
            "taken back": null,
            "worried": null,
            "guilty": null,
            "ashamed": null,
            "languid": null,
            "embarassed": null,
            "melancholic": null,
            "hesitant": null,
            "bored": null,
            "droopy": null,
            "doubtful": null,
            "distrustful": null,
            "hateful": null,
            "defient": null,
            "contemptous": null,
            "distressed": null,
            "disgusted": null,
            "loathing": null,
            "disontented": null,
            "bitter": null,
            "insulted": null,
            "startled": null,
            "disappointed": null,
            "miserable": null,
            "dissatisfied": null,
            "uncomfortable": null,
            "sad": null,
            "despondent": null,
            "depressed": null,
            "gloomy": null,
            "desperate": null,
            "wavering": null,
            "anxious": null,
            "dejected":null
        },
        limit: 4
    });
});